ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - supabase

patchedDependencies:
  '@dnd-kit/react@0.4.1-beta-20260419222523': patches/@dnd-kit__react@0.4.1-beta-20260419222523.patch
